@import gg.jte.Content
@param Content stuff

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Hexlet Javalin Example</title>
</head>
<body>
<p>
    <a href="/">Главная</a>
    <a href="/users">Список пользователей</a>
</p>
${stuff}
<h4><strong><span style="color: #808080;">Подвал</span></strong></h4>
</body>
</html>
